export const icoAcierto = '✅';
export const icoFallo = '❌';
export const icoPendiente = '⏳';
export const icoDinero = '💰';
export const icoUsuario = '👤';
export const icoClock = '🕒';
export const icoInfo = 'ℹ️';
export const icoWarning = '⚠️';
export const icoSunrise = '🌞';
